### ISSUE TITLE
Running exe on Windows 10 without GPU

### ISSUE THREAD

**Issue by weijiawang96** [Jhonve/GCN-Denoiser#5]
Dear Authors,

Can I run the exe on a Windows 10 without GPU? i.e. where I cannot set CUDA_PATH. 

Also, for Qt files (Qt5Core.dll, Qt5Gui.dll, Qt5OpenGL.dll, Qt5Widgets.dll), I can download them separately from https://www.dll-files.com/. But for Pytorch libraries (c10.dll, c10_cuda.dll, caffe2_nvrtc.dll, nvToolsExt61_1.dll, torch.dll) where should I get them from? And where should I put them after downloading them? 

Thank you very much!

**Comment by Jhonve** [comment]
Our executable demo can only be run with CUDA. If you want to use our code without GPU, you must modify our code and re-compile. We strongly recommend using devices with GPU because we need to predict normals in batches parallelly.
For the Pytorch library, you can download it from [Pytorch Website](https://pytorch.org/) (LibTorch for C++).

**Comment by weijiawang96** [comment]
Thank you. I'll try on my GPU machine and see if it can run.
